//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SSERVER_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_EDIT_PORTNO                 1000
#define IDC_BUTTON_START                1001
#define IDC_EDIT_NETMSG                 1002
#define IDC_BUTTON_STOP                 1003
#define IDC_COMBO_COMPORT               1004
#define IDC_BUTTON_OPEN                 1005
#define IDC_BUTTON_CLOSE                1006
#define IDC_EDIT_COMMSG                 1007
#define IDC_CHECK_SENDDATA              1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
