//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SCLIENT_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_EDIT_IPADDR                 1000
#define IDC_EDIT_PORTNO                 1001
#define IDC_EDIT_SENDDATA               1002
#define IDC_EDIT_RECVDATA               1003
#define IDC_BUTTON_LINK                 1004
#define IDC_BUTTON_UNLINK               1005
#define IDC_BUTTON_SEND                 1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
