//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SerialPortTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERIALPORTTEST_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDI_ICON_RED                    130
#define IDI_ICON_OFF                    131
#define IDC_EDIT_RECEIVEMSG             1000
#define IDC_BUTTON_SEND                 1001
#define IDC_CHECK_SWITCH1               1002
#define IDC_CHECK_SWITCH2               1003
#define IDC_COMBO_COMPORT               1004
#define IDC_BUTTON_OPEN                 1005
#define IDC_BUTTON_CLOSE                1006
#define IDC_EDIT_SENDMSG                1007
#define IDC_CHECK_SWITCH3               1008
#define IDC_CHECK_SWITCH4               1009
#define IDC_CHECK_SWITCH5               1010
#define IDC_CHECK_SWITCH6               1011
#define IDC_CHECK_SWITCH7               1012
#define IDC_CHECK_SWITCH8               1013
#define IDC_CHECK_SWITCH9               1014
#define IDC_EDIT_POSITION               1015
#define IDC_EDIT_VELOCITY               1016
#define IDC_COMBO_COMPORT2              1017
#define IDC_BUTTON_OPEN2                1018
#define IDC_BUTTON_CLOSE2               1019
#define IDC_STATIC_ICONS1               1020
#define IDC_STATIC_ICONS2               1021
#define IDC_STATIC_ICONS3               1022
#define IDC_STATIC_ICONS4               1023
#define IDC_STATIC_ICONS5               1024
#define IDC_STATIC_ICONS6               1025
#define IDC_STATIC_ICONS7               1026
#define IDC_STATIC_ICONS8               1027
#define IDC_STATIC_ICONS9               1028
#define IDC_EDIT_POSITION2              1029
#define IDC_EDIT_VELOCITY2              1030
#define IDC_EDIT_DISPDATA2              1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
