//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Term.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TERMTYPE                    129
#define IDD_DIALOG_COMSETTINGS          130
#define IDC_PORT                        1000
#define IDC_BAUD                        1001
#define IDC_DATABITS                    1002
#define IDC_PARITY                      1003
#define IDC_STOPBITS                    1004
#define IDC_NEWLINE                     1005
#define IDC_ECHO                        1006
#define IDC_FLOWCTRL                    1007
#define IDC_RADIO2                      1008
#define IDC_RADIO3                      1009
#define ID_COMM_SETTINGS                32771
#define ID_COMM_CONNECT                 32772
#define ID_COMM_DISCONNECT              32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
