language:
    - c
    - cpp

os:
    - linux

before_install:
    - sudo apt-get install cmake

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make

after_script:
    - if [ -f CTestTestfile.cmake ]; then ctest -V; fi
