//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SCOMM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SCOMM_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDI_ICON_XIAOFENGSTUDIO         131
#define IDC_CURSOR_HAND                 133
#define IDB_BITMAP_XFS                  134
#define IDI_ICON_OFF                    137
#define IDI_ICON_RED                    138
#define IDI_ICON_GREEN                  139
#define IDB_PINNED_BITMAP               142
#define IDB_UNPINNED_BITMAP             143
#define IDB_ANIM_IMGLIST                144
#define IDI_ICON_GJWTECH                145
#define IDC_COMBO_COMSELECT             1000
#define IDC_COMBO_SPEED                 1001
#define IDC_STATIC_STATUS               1004
#define IDC_BUTTON_OPENPORT             1005
#define IDC_CHECK_HEXRECIEVE            1006
#define IDC_BUTTON_CLEAR_RECI_AREA      1007
#define IDC_BUTTON_STOPDISP             1008
#define IDC_EDIT_RECIVE                 1009
#define IDC_BUTTON_MANUALSEND           1010
#define IDC_EDIT_CYCLETIME              1011
#define IDC_EDIT_SEND                   1012
#define IDC_CHECK_HEXSEND               1013
#define IDC_CHECK_AUTOSEND              1014
#define IDC_STATIC_XFS                  1015
#define IDC_STATIC_MAIL                 1016
#define IDC_STATIC_WWWXFS               1017
#define IDC_BUTTON_CLEARRECASENDA       1018
#define IDC_COMBO_PARITY                1020
#define IDC_COMBO_DATABITS              1021
#define IDC_COMBO_STOPBITS              1022
#define IDC_STATIC_XFS2                 1023
#define IDC_STATIC_MAILXFS1             1024
#define IDC_BUTTON_SAVEDATA             1026
#define IDC_EDIT_SAVEPATH               1027
#define IDC_BUTTON_DIRBROWSER           1028
#define IDC_BUTTON_FILEBROWSER          1030
#define IDC_EDIT_SENDFILE               1031
#define IDC_BUTTON_SENDFILE             1032
#define IDC_PROGRESS2                   1034
#define IDC_STATIC_OPENOFF              1035
#define IDC_STATIC_DATARECEIVE          1036
#define IDC_CHECK_AUTOCLEAR             1037
#define IDC_STATIC_RXCOUNT              1040
#define IDC_BUTTON_COUNTRESET           1041
#define IDC_LIST_RECEIVE                1042
#define IDC_BUTTON_CLOSE                1043
#define IDC_STATIC_TXCOUNT              1049
#define IDC_STATIC_SENDCHAR             1050
#define IDC_STATIC_CYCLETIME            1051
#define IDC_STATIC_MS                   1052
#define IDC_STATIC_GJW                  1053
#define IDC_STATIC10                    1054
#define IDC_STATIC11                    1055
#define IDC_STATIC12                    1056
#define IDC_STATIC13                    1057
#define IDC_STATIC14                    1058
#define IDC_BUTTON_PUSHPIN              1059
#define IDC_BUTTON1                     1060
#define IDC_BUTTON_HELP                 1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
